### PR TITLE
Always listen on the same port.

### PR DESCRIPTION
**Pull request by ojhaujjwal**

### CODE REVIEW

**Comment by ojhaujjwal** [comment]
any comments on this @samundrak ?

**Comment by samundrak** [comment]
we need to kill previous instance before using this one so there won't by any port conflict

**Comment by ojhaujjwal** [comment]
this is not really suitable for production use cases, only for development environment.
you have to look in the logs of a server for checking out where the application is running.

**Comment by samundrak** [comment]
ok, seems fine , will merge today

**Pull request merged**
